Develop
FredyArroyave12/React-Pokedex pull request #1
Opened 2021-08-09 19:10 UTC by FredyArroyave12

pokedex-v1

2021-08-10 14:16 UTC, hackeo1 requested changes
- check the naming convention on the images
- use either npm or yarn (remove one of the lock files, either package-lock.json or yarn.lock)

2021-08-10 14:16 UTC, hackeo1 commented on src/components/pokemonList/pokemonList.js
> +            .filter((item) => item.name.includes(props.navBar.searchContent))
filter must be done using the store

2021-08-10 14:27 UTC, jugonz31 approved these changes
Besides Carlos comments, it looks really good to me

2021-08-10 14:27 UTC, jugonz31 commented on public/index.html
> +    <title>React App</title>
Would be good to add a custom Title  to the page

2021-08-12 16:12 UTC, hackeo1 approved these changes

2021-08-12 18:37 UTC, merged